spring:
  datasource:
    url: jdbc:mysql://localhost/dept
    username: root
    password: chary@121
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084
  servlet:
    context-path: /department
